### ISSUE TITLE
JSONDecodeError when running main.py

### ISSUE THREAD

**Issue by Flute7** [dmunozv04/iSponsorBlockTV#1]
Hello, I have followed all setup instructions; Installed dependencies, grabbed Identifier and credentials and filed in config.json.
When running "python3 main.py" I get the following error. 
I have checked for issues in config.json and all looks ok. My knowledge of python is very limited so I am hoping you have an easy answer.

Thank You. Cool project, looking forward to the Docker deployment!

Traceback (most recent call last):
  File "main.py", line 134, in <module>
    atv_config, apikey, categories = load_config()
  File "main.py", line 130, in load_config
    config = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 4 column 347 (char 363)

**Comment by dmunozv04** [comment]
Hello, could you upload your config.json file, removing first the secrets, please? 
I can’t seem to replicate the issue

**Comment by Flute7** [comment]
Sure thing. I have renamed config.json to config.json.log to allow github upload.
I have replaced all secrets with template values.

[config.json.log](https://github.com/dmunozv04/iSponsorBlockTV/files/7991505/config.json.log)

**Comment by nocturne1** [comment]
> Sure thing. I have renamed config.json to config.json.log to allow github upload. I have replaced all secrets with template values.
@Flute7,  you might want to double-check that file you uploaded. It does not appear to be template values. I suggest you remove and revoke the API key to be safe.

**Comment by Flute7** [comment]
> > Sure thing. I have renamed config.json to config.json.log to allow github upload. I have replaced all secrets with template values.
> 
> 
> 
> @Flute7,  you might want to double-check that file you uploaded. It does not appear to be template values. I suggest you remove and revoke the API key to be safe.
> 
> 
> 
> 

Thanks but it's ok. I used an encryption generator to create the random values to look exactly like the real thing. They are in no way related to my actual credentials.

Appreciate the heads up anyway.

**Comment by dmunozv04** [comment]
@Flute7 could you try using docker, as it may be more reliable?

**Comment by Flute7** [comment]
Just pulled the docker image. Its working perfectly, thank you!

Two notes for reference to anyone who is setting this up,

To verify that this is functioning. iSponsorBlockTV successfully skips the sponsor segment starting at 1:05 in this video (https://www.youtube.com/watch?v=bFNJVaO9E-o).

Perhaps obvious, but the device discovery (port 5353) will conflict with other docker services you may be using such as Plex, Home Assistant, etc. You will need to change/disable these other 5353 ports to allow iSponsorBlockTV to work.
