### ISSUE TITLE
Suddenly stopped working entirely w/ no system changes/updates? Decoder/json err?

### ISSUE THREAD

**Issue by vulcanjedi** [dmunozv04/iSponsorBlockTV#180]
Before opening an issue make sure that there are no duplicates and that you are on the latest version.
suddenly spontaneously stopped working entirely.
 Main TV physical broke....while waiting for replacment to be delivered, migrated Chromecast dongle downstairs.  Delivery took excessive time, then when new tv arrived, connected to new tv and everything continued work no problem then yesterday evening just stopped. Reviewed container and realized errors

**Expected behavior**
None of the default expectant behvaiour works.  Autoskipping...etc

**Screenshots**

**iSponsorBlockTV server (please complete the following information):**
docker on linux/ubuntu v2.1.0

**Apple TV (please complete the following information):**
Chromecast 4k dongle

**Additional context**
#ssss

> ch
Filter...
Lines
100
Actions
 
 
 
      
  File "./iSponsorBlockTV/helpers.py", line 150, in app_start
  File "./iSponsorBlockTV/helpers.py", line 45, in __init__
  File "./iSponsorBlockTV/helpers.py", line 77, in __load
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 8 column 5 (char 160)
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
  File "./iSponsorBlockTV/helpers.py", line 150, in app_start
  File "./iSponsorBlockTV/helpers.py", line 45, in __init__
  File "./iSponsorBlockTV/helpers.py", line 77, in __load
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 8 column 5 (char 160)
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
  File "./iSponsorBlockTV/helpers.py", line 150, in app_start
  File "./iSponsorBlockTV/helpers.py", line 45, in __init__
  File "./iSponsorBlockTV/helpers.py", line 77, in __load
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 8 column 5 (char 160)
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
  File "./iSponsorBlockTV/helpers.py", line 150, in app_start
  File "./iSponsorBlockTV/helpers.py", line 45, in __init__
  File "./iSponsorBlockTV/helpers.py", line 77, in __load
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 8 column 5 (char 160)
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
  File "./iSponsorBlockTV/helpers.py", line 150, in app_start
  File "./iSponsorBlockTV/helpers.py", line 45, in __init__
  File "./iSponsorBlockTV/helpers.py", line 77, in __load
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 8 column 5 (char 160)
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
  File "./iSponsorBlockTV/helpers.py", line 150, in app_start
  File "./iSponsorBlockTV/helpers.py", line 45, in __init__
  File "./iSponsorBlockTV/helpers.py", line 77, in __load
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 8 column 5 (char 160)

**Comment by dmunozv04** [comment]
Hi @vulcanjedi please check that your `config.json` file is valid json. If you want, you can post it, censoring the sensitive data like the YouTube api key and the screen ids

**Comment by vulcanjedi** [comment]
I used the gui tool to create it and didnt mess with it at all?
________________________________

**Comment by vulcanjedi** [comment]
`
{
    "devices": [
        {
            "screen_id": "xxxxxxxxxxxxxxxxxxxxxxxx",
            "name": "YouTube on TV",
            "offset": 0
        },
    ],
    "apikey": "",
    "skip_categories": [
        "sponsor",
        "selfpromo",
        "intro",
        "music_offtopic"
    ],
    "channel_whitelist": [],
    "skip_count_tracking": true,
    "mute_ads": true,
    "skip_ads": true
}
`
