### ISSUE TITLE
iSponsorBlockTV stops working randomly, errors in console

### ISSUE THREAD

**Issue by nicktodorov** [dmunozv04/iSponsorBlockTV#203]
**Describe the bug**
iSponsorBlockTV running in docker on Mac. Clients are AppleTV and LG OLED. When starting the docker image and restarting the TV and AppleTV, everything works as configured - mute ads, auto skip unskippable,  skip sponsor segments.
But after few videos, it stops working.

**iSponsorBlockTV server (please complete the following information):**
 - OS: Docker on Mac with Apple silicon 

**Apple TV (please complete the following information):**
 - Device: Apple TV 4 - latest model, LG OLED 
 - OS: tvOS 18, webOS

**Logs**
`TV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Getting segments for next video: -NF-LnI5_U4
2024-12-03 02:57:48 2024-12-03 00:57:48,310 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Getting segments for next video: YK95-DMW6Z4
2024-12-03 02:57:49 2024-12-03 00:57:49,146 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Ad has ended, unmuting
2024-12-03 02:57:54 2024-12-03 00:57:54,351 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Playing video ISJTGqt2UcI with 0 segments
2024-12-03 02:57:56 2024-12-03 00:57:56,033 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Ad has ended, unmuting
2024-12-03 02:57:56 2024-12-03 00:57:56,033 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Getting segments for next video: AhAxLiGC7Pc
2024-12-03 02:57:56 2024-12-03 00:57:56,035 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Playing video ISJTGqt2UcI with 0 segments
2024-12-03 02:59:49 2024-12-03 00:59:49,693 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - ERROR - Handle subscribe failed, status 200 reason OK
2024-12-03 02:59:49 Traceback (most recent call last):
2024-12-03 02:59:49   File "/usr/local/lib/python3.11/site-packages/pyytlounge/wrapper.py", line 468, in subscribe
2024-12-03 02:59:49   File "/usr/local/lib/python3.11/site-packages/pyytlounge/wrapper.py", line 344, in _parse_event_chunks
2024-12-03 02:59:49   File "/usr/local/lib/python3.11/site-packages/pyytlounge/wrapper.py", line 142, in iter_response_lines
2024-12-03 02:59:49   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 317, in readline
2024-12-03 02:59:49   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 351, in readuntil
2024-12-03 02:59:49   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 312, in _wait
2024-12-03 02:59:49 asyncio.exceptions.CancelledError
2024-12-03 02:59:49 2024-12-03 00:59:49,895 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Getting segments for next video: AhAxLiGC7Pc
2024-12-03 02:59:49 2024-12-03 00:59:49,896 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Connected to device YouTube on TV (My ATV)
2024-12-03 02:59:49 2024-12-03 00:59:49,896 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Subscribing to lounge
2024-12-03 02:59:49 2024-12-03 00:59:49,898 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Subscribing to lounge id AGdO5p_HDaVDKtQlk-5KMpxGKo4fXWAzFePrrBejn1T_I7tcKj6EOng5nYyYlkqhgOCfTydYeG4ArJDZoVKm8XHg1COwEj_v03RVlBx6kx2YpdXLoAeLhYs
2024-12-03 02:59:50 2024-12-03 00:59:50,122 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Ad has ended, unmuting
2024-12-03 02:59:50 2024-12-03 00:59:50,124 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Playing video ISJTGqt2UcI with 0 segments
2024-12-03 03:02:03 2024-12-03 01:02:03,484 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - ERROR - Handle subscribe failed, status 200 reason OK
2024-12-03 03:02:03 Traceback (most recent call last):
2024-12-03 03:02:03   File "/usr/local/lib/python3.11/site-packages/pyytlounge/wrapper.py", line 468, in subscribe
2024-12-03 03:02:03   File "/usr/local/lib/python3.11/site-packages/pyytlounge/wrapper.py", line 344, in _parse_event_chunks
2024-12-03 03:02:03   File "/usr/local/lib/python3.11/site-packages/pyytlounge/wrapper.py", line 142, in iter_response_lines
2024-12-03 03:02:03   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 317, in readline
2024-12-03 03:02:03   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 351, in readuntil
2024-12-03 03:02:03   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 312, in _wait
2024-12-03 03:02:03 asyncio.exceptions.CancelledError
2024-12-03 03:02:03 2024-12-03 01:02:03,678 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Connected to device YouTube on TV (My ATV)
2024-12-03 03:02:03 2024-12-03 01:02:03,678 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Subscribing to lounge
2024-12-03 03:02:03 2024-12-03 01:02:03,682 - iSponsorBlockTV-vrk8bp99qc4l1noc6sg42cgj3v - INFO - Subscribing to lounge id `

**Comment by dmunozv04** [comment]
Hi there, YouTube sometimes likes to error and close the subscription to the device, but normally it should just reconnect a few seconds after. It would seem like it's happening since it tries to reconnect in the last line on the log. 
If it doesn't reconnect, please run iSponsorBlockTV with the `--debug` flag and send the logs, since this doesn't give me al the information.

**Comment by nicktodorov** [comment]
Sorry for the delay. here is the log with debug on.
I think now it is even worse. It almost never triggers to mute or auto skip adds.
[log.txt](https://github.com/user-attachments/files/18054159/log.txt)

**Comment by dmunozv04** [comment]
@nicktodorov could you test with the latest version? We've changed some things and they might've fixed your problems
