### ISSUE TITLE
Docker Container Continuously Crashing

### ISSUE THREAD

**Issue by mvicari** [dmunozv04/iSponsorBlockTV#45]
Tried recreating config file and recreating the docker container:

```Traceback (most recent call last):
  File "/app/main.py", line 3, in <module>
    helpers.app_start()
  File "/app/iSponsorBlockTV/helpers.py", line 43, in app_start
    config_setup.main(config, args.file, args.debug)
  File "/app/iSponsorBlockTV/config_setup.py", line 163, in main
    loop.run_until_complete(web_session.close())
                            ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'web_session' where it is not associated with a value

**Comment by dmunozv04** [comment]
It should be fixed on the latest docker build (made 1 minute ago). Thanks for letting me know
