### ISSUE TITLE
Docker image no longer recognize my config.json

### ISSUE THREAD

**Issue by L041S** [dmunozv04/iSponsorBlockTV#47]
Hello,
I realized that since several days ads were not skipped anymore. I checked the container and saw that it crashed. When I try to launch I now got the message "invalid config file, please run with --setup"

Maybe it is related to a recent commit ?

Anyway, I tried to reconfigure it, with --setup but got

`Found 1 Apple TV(s) in config.json. Add more? (y/n) Traceback (most recent call last):
  File "/app/main.py", line 3, in <module>
    helpers.app_start()
  File "/app/iSponsorBlockTV/helpers.py", line 43, in app_start
    config_setup.main(config, args.file, args.debug)
  File "/app/iSponsorBlockTV/config_setup.py", line 67, in main
    input("Found {} Apple TV(s) in config.json. Add more? (y/n) ".format(num_atvs))
EOFError: EOF when reading a line
`

**Comment by oxixes** [comment]
Did you type anything when it asked you yes or no? Or you simply hit enter? 

You need to type `n` for `no` instead of just pressing enter.

**Comment by L041S** [comment]
Negative, I got the message as soon as I press enter when launching the container without the possibility to press n

**Comment by oxixes** [comment]
@dmunozv04 should be able to this this further, but it may be related to your setup not allowing user input. You can modify the config file manually if needed (although I told you what to add, you can look the config file template to get an idea of the structure).

**Comment by dmunozv04** [comment]
It looks like you’re not running the setup in interactive mode, it requires specifying the -it flag like this: 
```sh
docker run --rm -it \
--network=host \
-v /PATH_TO_YOUR_CONFIG.json:/app/config.json \
ghcr.io/dmunozv04/isponsorblocktv \
--setup
```
That should do the trick. Please let me know if that works
