### ISSUE TITLE
Docker container restarts over and over

### ISSUE THREAD

**Issue by noktulo** [dmunozv04/iSponsorBlockTV#54]
I attempted using the MacOS installer, but since I'm on an M1 it didn't work and I'm using Docker. 

I entered the first docker command, and it didn't find my ATV:

```Creating config file
Found 0 Apple TV(s) in config.json. Add more? (y/n) y
No devices found
Rewriting atvs (don't worry if none were saved before)
```

I tried running the container using the command provided anyway, and it restarts every second or so. Here's an example of what shows up in the logs:

```
Traceback (most recent call last):
2023-07-15 11:22:44   File "/app/main.py", line 3, in <module>
2023-07-15 11:22:44     helpers.app_start()
2023-07-15 11:22:44   File "/app/iSponsorBlockTV/helpers.py", line 53, in app_start
2023-07-15 11:22:44     main.main(
2023-07-15 11:22:44   File "/app/iSponsorBlockTV/main.py", line 146, in main
2023-07-15 11:22:44     for i in atv_configs:
2023-07-15 11:22:44 TypeError: 'NoneType' object is not iterable
2023-07-15 11:22:44 Unclosed client session
2023-07-15 11:22:44 client_session: <aiohttp.client.ClientSession object at 0xffff88ce5110>
```

**Comment by dmunozv04** [comment]
The current version of iSponsorblockTV can’t be run on docker on macOS/Windows because they lack the docker `net:host` network mode, required by AirPlay.

**Comment by dmunozv04** [comment]
Your best option is to manually install python and iSponsorblockTV, which could be made easier in the future if we release it on pypi (PR’s would be welcome to do it)

**Comment by noktulo** [comment]
Thanks for the info! I ended up installing it via Docker on my Synology and got it working.

**Comment by bertybuttface** [comment]
Anyone using home assistant can also install the home assistant plugin I made https://github.com/bertybuttface/addons/tree/main/isponsorblocktv

Please create an issue if you have trouble getting it setup. The documentation is severely lacking for now, sorry.

**Comment by dmunozv04** [comment]
Should be fixed on V2
