### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by ggauzin** [dmunozv04/iSponsorBlockTV#81]
>>>python main.py
Traceback (most recent call last):
  File "D:\iSponsorBlockTV-2.0.2\main.py", line 1, in <module>
    from iSponsorBlockTV import helpers
  File "D:\iSponsorBlockTV-2.0.2\iSponsorBlockTV\helpers.py", line 8, in <module>
    from . import config_setup, main, setup_wizard
  File "D:\iSponsorBlockTV-2.0.2\iSponsorBlockTV\config_setup.py", line 5, in <module>
    from . import api_helpers, ytlounge
  File "D:\iSponsorBlockTV-2.0.2\iSponsorBlockTV\api_helpers.py", line 1, in <module>
    from cache import AsyncTTL, AsyncLRU
ModuleNotFoundError: No module named 'cache'

from source, win11

**Comment by dmunozv04** [comment]
It seems like you’re missing a dependency, make sure to run `pip install -r requirements.txt`

**Comment by ggauzin** [comment]
i think it didn't run properly, but it is working good rn
